name        : sound-theme-freedesktop
version     : 0.8
release     : 2
source      :
    - http://people.freedesktop.org/~mccann/dist/sound-theme-freedesktop-0.8.tar.bz2 : cb518b20eef05ec2e82dda1fa89a292c1760dc023aba91b8aa69bafac85e8a14
homepage    : www.freedesktop.org/wiki/Specifications/sound-theme-spec/
license     :
    - GPLv2+
summary     : Freedesktop reference sound theme
description : |
    Freedesktop reference sound theme
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
